### ISSUE TITLE
Redirect error

### ISSUE THREAD

**Issue by mikan01** [karl-chan/google-drive-torrent#4] opened 2017-07-20 16:25 UTC
I am getting strange redirect error post oauth screen after I select the e-mail and allows app to access my Google Drive, the app suddenly shows error screen and redirects to the default homepage.

I have deployed this app many times on heroku and on vps before, it used to work fine but now it stopped working. Please check if possible. Thanks :)

P.S. http://google-drive-torrent.herokuapp.com/ still seems to be working fine for some reason and there's only issues when we deploy a new app. 

http://imgur.com/NDPkY5S

http://imgur.com/JrK7OLf

**Comment by kxbeqiluxspam** [comment] 2017-08-02 15:31
True, i am facing the same issue. Not able to make this code work anywhere because of that

**Comment by pidutv** [comment] 2017-08-09 05:25
I am facing the same issue :(

**Comment by VerliererK** [comment] 2017-08-20 12:15
enable google+ API and google drive API

**Comment by nk932714** [comment] 2017-11-09 08:21
error after enabling google+ API & drive API

"**Sorry!  Something went wrong**"

**Comment by xxx31fr** [comment] 2017-11-29 20:35
Hello, 
I get an error when i click on Log-in button:
<img width="737" alt="karlto" src="https://user-images.githubusercontent.com/8737328/33397800-174e190c-d54d-11e7-88b4-e47d23706b2c.png">

I don't understand how to fix the problem with uri mismatch...

Thanks for your help

**Comment by lakhobim** [comment] 2018-02-09 11:02
still error with some thing went wrong  how to fix that thanks

**Comment by mrtaurusp** [comment] 2018-05-08 14:42
The bug still occurs.

**Comment by DIASILEDU** [comment] 2019-04-18 15:08
Im having this error, is there any way to fix it? Already enabled Drive and G+ API

**Comment by ChandraSumer** [comment] 2019-04-25 23:00
Go to credentials on console.developers.google.com and add "http://localhost:3000/login-callback " to Authorised redirect URIs in the client id you created for the application.

**Comment by bodoamat-git** [comment] 2019-08-24 10:44
> Im having this error, is there any way to fix it? Already enabled Drive and G+ API

are you sure to enabled it ?

**Comment by karl-chan** [comment] 2019-12-26 20:52
Duplicate of https://github.com/karl-chan/google-drive-torrent/issues/17

**Closed as completed by karl-chan** 2019-12-26 20:52 UTC
